#! /bin/sh

# * ############################################################################
# * Window manager independent hotkeys
# * ############################################################################

# Open the default terminal emulator. If it can't, start kitty
super + Return
    if [ -x $TERM ]; then \
        $TERM; \
    else \
        if [ -x $TERMINAL ]; then \
            $TERMINAL; \
        else \
            kitty; \
        fi; \
    fi

# program launcher
super + space
    rofi -modi drun -show drun -line-padding 4 \
                -columns 2 -padding 50 -hide-scrollbar -terminal xfce4-terminal \
                -show-icons -drun-icon-theme "Qogir-dark" -font "Droid Sans Regular 10" -dpi 216

# show open window
super + ctrl + space
    rofi -modi drun -show window -line-padding 4 \
                -columns 2 -padding 50 -hide-scrollbar -terminal xfce4-terminal \
                -show-icons -drun-icon-theme "Qogir-dark" -font "Droid Sans Regular 10" -dpi 216

# show ssh sesssions
super + shift + space
    rofi -modi drun -show ssh -line-padding 4 \
                -columns 2 -padding 50 -hide-scrollbar -terminal xfce4-terminal \
                -show-icons -drun-icon-theme "Qogir-dark" -font "Droid Sans Regular 10" -dpi 216

# power-menu
super + shift + e
     ~/.config/rofi/powermenu.sh

# make sxhkd reload its configuration files:
super + Escape
    pkill -USR1 -x sxhkd



# * ############################################################################
# * BSPWM hotkeys
# * ############################################################################

# quit/restart bspwm
super + alt + shift + {q,r}
    bspc {quit,wm -r}

# close and kill
super + {_,shift + }q
    bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
    bspc desktop -l next

# # send the newest marked node to the newest preselected node
# super + y
    # bspc node newest.marked.local -n newest.!automatic.local
#
# # swap the current node and the biggest window
# super + g
    # bspc node -s biggest.window


########################################
# State, flags
########################################

# set the window state
super + {t,shift + t,s,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
    bspc node -g {marked,locked,sticky,private}


########################################
# Focus, swap
########################################

# focus the node in the given direction
super + {_,shift + }{j,k,i,l}
    bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
    bspc node -f @{parent,brother,first,second}

# focus the next/previous window in the current desktop
alt + {_,shift + }Tab
    bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
    bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {dead_grave,grave,Tab}
    bspc {node,node,desktop} -f last

# # focus the older or newer node in the focus history
# super + {o,i}
    # bspc wm -h off; \
    # bspc node {older,newer} -f; \
    # bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-5,F1,F2,F3,F4,F5}
    bspc {desktop -f,node -d} '^{1-9,10}'


# ########################################
# # Preselect
# ########################################

# # preselect the direction
# super + ctrl + {h,j,k,l}
#     bspc node -p {west,south,north,east}

# # preselect the ratio
# super + ctrl + {1-9}
#     bspc node -o 0.{1-9}

# # cancel the preselection for the focused node
# super + ctrl + space
#     bspc node -p cancel

# # cancel the preselection for the focused desktop
# super + ctrl + shift + space
#     bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel


########################################
# Move, resize
########################################

# expand a window by moving one of its side outward
super + alt + {j,k,i,l}
    bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {j,k,i,l}
    bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
    bspc node -v {-20 0,0 20,0 -20,20 0}



# * ############################################################################
# * Special hotkeys
# * ############################################################################

# Multimedia keys
{XF86AudioRaiseVolume, ctrl + F2}
    amixer -q set Master 2%+ unmute

{XF86AudioLowerVolume, ctrl + F3}
    amixer -q set Master 2%- unmute

{XF86AudioMute, alt + F7}
    amixer -D pulse sset Master toggle-mute

# Foobar2000 media controls
{XF86AudioPlay, XF86AudioPause, ctrl + F1}
    WINEDEBUG=fixme-all WINEPREFIX=/home/vini/wineprefixes/foobar2000 wine /home/vini/wineprefixes/foobar2000/drive_c/Program\ Files\ \(x86\)/foobar2000/foobar2000.exe /playpause

# amixer -q set Master toggle
# Simple amixer command seems to have problems unmuting device

# # Brightness up
# XF86MonBrightnessUp
    # xbacklight -inc 5
#
# # And brightness down
# XF86MonBrightnessDown
    # xbacklight -dec 5

# Screenshot with Flameshot
{_,ctrl,super} + Print
    QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCREEN_SCALE_FACTORS="" flameshot {screen -c,gui,full -c}

# # Screenshotting (old methods from Endeavour OS)
# Print
#     scrot "$(xdg-user-dir PICTURES)/screenshot-$(date +%F_%T).png"

# super + Print
#     ~/.config/bspwm/scripts/screenshot.sh

# Shortcuts
super + ctrl + b
    librewolf

super + ctrl + e
    thunar

super + ctrl + c
    speedcrunch

super + ctrl + f
    WINEDEBUG=fixme-all WINEPREFIX=/home/vini/wineprefixes/foobar2000 wine /home/vini/wineprefixes/foobar2000/drive_c/Program\ Files\ \(x86\)/foobar2000/foobar2000.exe

super + ctrl + t
    telegram-desktop

super + ctrl + d
    /home/vini/.local/bin/discord

# VS Code
super + ctrl + v
    code

super + ctrl + p
    postman

# super + F1
    # ~/.config/bspwm/scripts/keybindings_rofi.sh
